### ISSUE TITLE
breeze-gtk 5.8.4

### ISSUE THREAD

**Issue by Geyup** [Sadi58/Breeze-Theme#1]
Hello,

You don't have an 'Issues' section for the breeze-gtk ...

https://github.com/Sadi58/breeze-gtk

Using gtk+3-3.18 and SpaceFM 1.0.5, when I launch SpaceFM using Breeze-gtk I get this in the terminal;

** (spacefm:6308): WARNING **: Invalid borders specified for theme pixmap:
        /home/foo/.themes/Breeze-gtk/gtk-2.0/../assets/line-h.png,
borders don't fit within the image

Great theme, keep up the great work!

**Comment by Geyup** [comment]
Something else I noticed, I'm assuming because of the slight shadow around buttons and drop downs, which gives them a slight elevated look? Because in the dark theme, it appears flatter, shouldn't the dark them also appear the same, and not have the buttons and drop downs appear flatter?

Hmm

**Comment by Sadi58** [comment]
Sorry, I'm just trying to make this beautiful KDE theme fully usable in GTK environment, and particularly under Ubuntu, in spite of the fact that I'm just an end-user with no formal qualifications in this field - just trying to learn...
I've done this job better for GTK 3.18 here: https://github.com/Sadi58/Breeze-Theme
And I'm only at the beginning of the road for GTK 3.20 at https://github.com/Sadi58/breeze-gtk
So perhaps you might get a better result if you try the former one...

**Comment by Geyup** [comment]
Ok thanks

**Comment by Sadi58** [comment]
Actually most themes have such minor warning/error messages in the terminal as far as I can see (although ideally a perfect theme shouldn't ;-)
If you don't see any other visible problem, that should be fine I guess.
Otherwise perhaps you can add a screenshot and we can see if it can be fixed (without causing other problems (in other apps).

**Comment by Geyup** [comment]
I'm a geek I know, just reporting it, case you wanted to look into it...

This type of warning I've never seen in Linux, is also why I reported it.

**Comment by Sadi58** [comment]
Thanks, but unfortunately I'm almost opposite of geek ( maybe an over-ambitious intermediate-lever user ; -)
So I have no idea what that problem is and what I can do about it.
Essentially I just tried to make this beautiful theme usable under Ubuntu 16.04 as well.
Now I'm working on the current one updated for GTK 3.20 (i.e. Ubuntu 16.10) which is more difficult (and probably I'll give up this "over-ambitious" idea altogether ;-)

**Comment by Geyup** [comment]
No worries and thanks, you did good! :)
